### ISSUE TITLE
TypeError: _require is not a function

### ISSUE THREAD

**Issue by alexmartynenkozoomin** [markedjs/html-differ#231]
```
  ● Test suite failed to run

    TypeError: _require is not a function

    >  1 | import { HtmlDiffer } from '@markedjs/html-differ';
         | ^

      at Object._require (node_modules/@markedjs/html-differ/lib/defaults.js:2:30)
      at Object.require (node_modules/@markedjs/html-differ/lib/HtmlDiff.js:2:1)
      at Object.require (node_modules/@markedjs/html-differ/lib/index.js:1:1)

```
![image](https://user-images.githubusercontent.com/108810605/229326363-ad2aff88-d428-4610-be76-70f61385990e.png)

`package.json`
```
...
"@markedjs/html-differ": "4.0.2",
"@babel/core": "7.19.3",
"@babel/preset-env": "7.19.3",
@babel/plugin-transform-runtime: "7.21.4",
"babel-plugin-transform-import-meta": "2.2.0",
"jest": "28.1.1",
...
```
`jest.config.ts`
```
const esModules = ['@markedjs/html-differ'].join('|');

const config = {
  ...
  transform: {
    [`(${esModules}).+\\.js$`]: require.resolve('babel-jest'),
   ...
  },
  transformIgnorePatterns: [
    `/node_modules/(?!${esModules})`,
   ...
  ],
  ...
}
```
`babel.config.js`
```
module.exports = {
  env: {
    test: {
      presets: ['@babel/preset-env'],
      plugins: ['@babel/plugin-transform-runtime', 'babel-plugin-transform-import-meta'],
    },
  },
};
```

The issue can be resolved by downgrading to `"@markedjs/html-differ": "3.0.4",` without using the abovementioned configurations.

**Comment by UziTech** [comment]
Yup v4 moved to esm
